# Generated by Django 5.0.7 on 2024-07-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variation_code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='b_DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.a_network')),
            ],
        ),
        migrations.CreateModel(
            name='c_DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation_code', models.CharField(max_length=3, null=True)),
                ('validity', models.CharField(max_length=100, null=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.b_datatype')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_app.a_network')),
            ],
        ),
        migrations.CreateModel(
            name='DataTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=11)),
                ('client_reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('webhook_received', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('auto_refund_status', models.CharField(max_length=50)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_no', models.CharField(max_length=50)),
                ('true_response', models.CharField(max_length=50)),
                ('data_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.c_dataplan')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.b_datatype')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.a_network')),
            ],
        ),
    ]
