# Generated by Django 5.0.7 on 2024-07-30 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_a_network_b_datatype_c_dataplan_datatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
